<?php

declare(strict_types=1);

namespace BillTo\WooCommerce\Admin;

use BillTo\Shop\OAuth\OAuthClient;
use BillTo\Shop\OAuth\Pkce;
use BillTo\WooCommerce\Api\OAuth\Connection;
use BillTo\WooCommerce\Support\Options;

/**
 * "Connect to BillTo" flow in the shop admin.
 *
 * Runs Dynamic Client Registration followed by the Authorization Code flow with PKCE: the
 * installation registers its own client credentials using a registration code generated by the
 * merchant, then the merchant approves the connection in BillTo and picks the company the token
 * is scoped to. The PKCE verifier and the state value stay on the shop server.
 */
final class OAuthConnectController
{
    public const ACTION_CONNECT = 'billto_oauth_connect';

    public const ACTION_CALLBACK = 'billto_oauth_callback';

    public const ACTION_DISCONNECT = 'billto_oauth_disconnect';

    /** Zgody, o które wtyczka prosi. Węziej się nie da - to minimum dla fakturowania zamówień. */
    private const SCOPES = [
        'orders:read', 'orders:write',
        'invoices:read', 'invoices:write',
        'contractors:read', 'contractors:write',
        'products:read',
    ];

    private const TRANSIENT_FLOW = 'billto_wc_oauth_flow';

    public function __construct(private Options $options, private Connection $connection) {}

    /**
     * Software statement id of this plugin, read from the BillTo instance the shop is configured
     * against.
     *
     * Production and sandbox are separate instances with separate application registries, so an
     * id issued in one does not exist in the other; a value shipped in the package would only
     * work in a single environment and would leave the custom API address unusable. Null when
     * the instance has no entry for this plugin, or has not granted it dynamic registration.
     */
    private function softwareStatementId(): ?string
    {
        $response = wp_remote_get(
            rtrim($this->options->baseUrl(), '/').'/plugins/woocommerce/latest',
            ['timeout' => 15, 'headers' => ['Accept' => 'application/json']]
        );

        if (is_wp_error($response) || (int) wp_remote_retrieve_response_code($response) !== 200) {
            return null;
        }

        $body = json_decode((string) wp_remote_retrieve_body($response), true);
        $id = is_array($body) ? ($body['software_statement_id'] ?? null) : null;

        return is_string($id) && $id !== '' ? $id : null;
    }

    public function register(): void
    {
        add_action('admin_post_'.self::ACTION_CONNECT, [$this, 'connect']);
        add_action('admin_post_'.self::ACTION_CALLBACK, [$this, 'callback']);
        add_action('admin_post_'.self::ACTION_DISCONNECT, [$this, 'disconnect']);
        add_action('admin_notices', [$this, 'renderResultNotice']);
    }

    /**
     * Result of the last connect attempt, passed back in `billto_oauth`. Without this the flow
     * redirects to the settings tab and says nothing, so a failure looks like a no-op button.
     */
    public function renderResultNotice(): void
    {
        // Read only to render a message; no state change, so no nonce here.
        $result = isset($_GET['billto_oauth']) ? sanitize_key(wp_unslash((string) $_GET['billto_oauth'])) : '';

        if ($result === '') {
            return;
        }

        $messages = [
            'connected' => [true, __('Sklep został połączony z BillTo.', 'billto-woocommerce')],
            'disconnected' => [true, __('Sklep został odłączony od BillTo.', 'billto-woocommerce')],
            'missing_code' => [false, __('Podaj kod instalacyjny wygenerowany w BillTo (Ustawienia → Integracje → Autoryzowane aplikacje).', 'billto-woocommerce')],
            'registration_failed' => [false, __('BillTo odrzuciło rejestrację tej instalacji. Kod instalacyjny jest jednorazowy i ważny dwie minuty - wygeneruj nowy i spróbuj ponownie.', 'billto-woocommerce')],
            'statement_unavailable' => [false, __('Nie udało się pobrać danych rejestracji z BillTo. Sprawdź adres API w ustawieniach wtyczki i spróbuj ponownie.', 'billto-woocommerce')],
            'state_mismatch' => [false, __('Odpowiedź z BillTo nie pasuje do rozpoczętego połączenia. Rozpocznij łączenie ponownie.', 'billto-woocommerce')],
            'denied' => [false, __('Połączenie nie zostało zatwierdzone w BillTo.', 'billto-woocommerce')],
            'exchange_failed' => [false, __('Nie udało się dokończyć połączenia z BillTo. Spróbuj ponownie.', 'billto-woocommerce')],
        ];

        if (! isset($messages[$result])) {
            return;
        }

        [$success, $message] = $messages[$result];

        printf(
            '<div class="notice notice-%s is-dismissible"><p>%s</p></div>',
            $success ? 'success' : 'error',
            esc_html($message)
        );
    }

    public function connect(): void
    {
        if (! current_user_can('manage_woocommerce')) {
            wp_die(esc_html__('Brak uprawnień.', 'billto-woocommerce'));
        }

        // The nonce check stays in the same function that reads $_POST, where phpcs can see it.
        check_admin_referer(self::ACTION_CONNECT);

        // Registration code entered by the merchant, not a value shipped in the package: it is
        // generated in BillTo, short-lived and single use.
        $code = isset($_POST['billto_registration_code'])
            ? sanitize_text_field(wp_unslash((string) $_POST['billto_registration_code']))
            : '';

        if ($code === '' && $this->connection->clientId() === '') {
            $this->redirectBack('missing_code');
        }

        $statementId = $this->softwareStatementId();

        if ($statementId === null) {
            $this->redirectBack('statement_unavailable');
        }

        if (! $this->connection->ensureRegistered((string) $statementId, $code, $this->redirectUri())) {
            $this->redirectBack('registration_failed');
        }

        $verifier = Pkce::verifier();
        $state = Pkce::state();

        // The verifier and the state live on the server, not in the redirect URL, and expire
        // after 15 minutes.
        set_transient(self::TRANSIENT_FLOW, ['verifier' => $verifier, 'state' => $state], 15 * MINUTE_IN_SECONDS);

        wp_redirect($this->oauth()->authorizationUrl(
            $this->connection->clientId(),
            $this->redirectUri(),
            self::SCOPES,
            $state,
            $verifier
        ));
        exit;
    }

    public function callback(): void
    {
        if (! current_user_can('manage_woocommerce')) {
            wp_die(esc_html__('Brak uprawnień.', 'billto-woocommerce'));
        }

        $flow = get_transient(self::TRANSIENT_FLOW);
        delete_transient(self::TRANSIENT_FLOW);

        $state = isset($_GET['state']) ? sanitize_text_field(wp_unslash((string) $_GET['state'])) : '';
        $code = isset($_GET['code']) ? sanitize_text_field(wp_unslash((string) $_GET['code'])) : '';

        // The state comparison is what distinguishes a callback from this request from a
        // planted one.
        if (! is_array($flow) || ! hash_equals((string) ($flow['state'] ?? ''), $state)) {
            $this->redirectBack('state_mismatch');
        }

        if ($code === '') {
            // The merchant denied the request, or BillTo rejected it; not a failure.
            $this->redirectBack('denied');
        }

        $tokens = $this->oauth()->exchangeCode(
            $this->connection->clientId(),
            $this->connection->clientSecret(),
            $this->redirectUri(),
            $code,
            (string) $flow['verifier']
        );

        if ($tokens === null) {
            $this->redirectBack('exchange_failed');
        }

        $this->connection->store($tokens);

        $this->redirectBack('connected');
    }

    public function disconnect(): void
    {
        $this->authorizeRequest(self::ACTION_DISCONNECT);

        $this->connection->disconnect();

        $this->redirectBack('disconnected');
    }

    private function oauth(): OAuthClient
    {
        return new OAuthClient($this->options->oauthBaseUrl(), new \BillTo\WooCommerce\Api\OAuth\WpHttpPost);
    }

    /**
     * Redirect URI, compared by BillTo during the code exchange. It has to match the registered
     * value, so changing the shop address requires registering the installation again.
     */
    private function redirectUri(): string
    {
        return admin_url('admin-post.php?action='.self::ACTION_CALLBACK);
    }

    private function authorizeRequest(string $action): void
    {
        if (! current_user_can('manage_woocommerce')) {
            wp_die(esc_html__('Brak uprawnień.', 'billto-woocommerce'));
        }

        check_admin_referer($action);
    }

    private function redirectBack(string $result): void
    {
        wp_redirect(add_query_arg(
            'billto_oauth',
            $result,
            admin_url('admin.php?page=wc-settings&tab=billto')
        ));
        exit;
    }
}
