<?php

declare(strict_types=1);

namespace BillTo\WooCommerce\Api\OAuth;

use BillTo\Shop\OAuth\OAuthClient;
use BillTo\Shop\OAuth\TokenSet;
use BillTo\WooCommerce\Support\Logger;
use BillTo\WooCommerce\Support\Options;

/**
 * OAuth connection state of this shop: the installation's own client credentials and its token
 * pair. Each installation registers its own credentials through Dynamic Client Registration.
 *
 * Token refresh happens here rather than in the API client, so the token is exchanged before a
 * request is sent instead of after it fails.
 */
final class Connection
{
    private const OPT_CLIENT_ID = 'oauth_client_id';

    private const OPT_CLIENT_SECRET = 'oauth_client_secret';

    private const OPT_ACCESS_TOKEN = 'oauth_access_token';

    private const OPT_REFRESH_TOKEN = 'oauth_refresh_token';

    private const OPT_EXPIRES_AT = 'oauth_expires_at';

    private const OPT_COMPANY = 'oauth_company';

    /** Option keys are read through `Options::PREFIX`; the BillTo address is resolved by the caller. */
    public function __construct(
        private Logger $logger,
        private OAuthClient $oauth,
    ) {}

    public function isConnected(): bool
    {
        return $this->tokens() !== null;
    }

    /** Name of the company the shop was authorised for, shown in the settings. */
    public function companyName(): string
    {
        return (string) get_option(Options::PREFIX.self::OPT_COMPANY, '');
    }

    public function clientId(): string
    {
        return (string) get_option(Options::PREFIX.self::OPT_CLIENT_ID, '');
    }

    public function clientSecret(): string
    {
        return (string) get_option(Options::PREFIX.self::OPT_CLIENT_SECRET, '');
    }

    /**
     * Registers this installation in BillTo unless it already holds credentials.
     *
     * Idempotent: a repeated call does not create a second client.
     */
    public function ensureRegistered(string $softwareStatementId, string $registrationCode, string $redirectUri): bool
    {
        if ($this->clientId() !== '' && $this->clientSecret() !== '') {
            return true;
        }

        // The software statement id identifies the vendor and ships with the plugin; the
        // registration code is generated by the merchant in BillTo and is valid for two
        // minutes. Registration requires both.
        $credentials = $this->oauth->register(
            $softwareStatementId,
            $registrationCode,
            $this->installationName(),
            $redirectUri
        );

        if ($credentials === null) {
            $this->logger->error('[BillTo OAuth] rejestracja instalacji odrzucona przez BillTo');

            return false;
        }

        update_option(Options::PREFIX.self::OPT_CLIENT_ID, $credentials['client_id'], false);
        update_option(Options::PREFIX.self::OPT_CLIENT_SECRET, $credentials['client_secret'], false);

        return true;
    }

    /**
     * Stores the token pair returned by the authorization code exchange.
     *
     * @param  array{access_token: string, refresh_token: ?string, expires_in: int}  $response
     */
    public function store(array $response, string $companyName = ''): void
    {
        $set = TokenSet::fromTokenResponse($response);

        update_option(Options::PREFIX.self::OPT_ACCESS_TOKEN, $set->accessToken, false);
        update_option(Options::PREFIX.self::OPT_REFRESH_TOKEN, (string) $set->refreshToken, false);
        update_option(Options::PREFIX.self::OPT_EXPIRES_AT, $set->expiresAt, false);

        if ($companyName !== '') {
            update_option(Options::PREFIX.self::OPT_COMPANY, $companyName, false);
        }
    }

    /**
     * Valid access token, or null when the shop is not connected or the refresh failed.
     *
     * Returns null rather than throwing, so the caller can fall back to a token stored in the
     * settings by an installation predating OAuth.
     */
    public function accessToken(): ?string
    {
        $set = $this->tokens();

        if ($set === null) {
            return null;
        }

        if (! $set->needsRefresh()) {
            return $set->accessToken;
        }

        if (! $set->canRefresh()) {
            // Without a refresh token the shop has to be authorised again by hand, so the
            // state is recorded instead of leaving the caller with repeated 401s.
            $this->logger->error('[BillTo OAuth] token wygasł i nie ma czym go odświeżyć - wymagana ponowna autoryzacja');

            return null;
        }

        $response = $this->oauth->refresh($this->clientId(), $this->clientSecret(), (string) $set->refreshToken);

        if ($response === null) {
            $this->logger->error('[BillTo OAuth] odświeżenie tokenu odrzucone - wymagana ponowna autoryzacja');

            return null;
        }

        // The refresh token is single use: BillTo revokes it during the exchange, so the new
        // pair is stored before the next request.
        $this->store($response);

        return $response['access_token'];
    }

    public function disconnect(): void
    {
        foreach ([self::OPT_ACCESS_TOKEN, self::OPT_REFRESH_TOKEN, self::OPT_EXPIRES_AT, self::OPT_COMPANY] as $key) {
            delete_option(Options::PREFIX.$key);
        }

        // The installation credentials (client_id/secret) are kept: disconnecting withdraws the
        // authorisation for a company, so reconnecting skips registration.
    }

    /**
     * Clears the installation credentials as well.
     *
     * Used when the environment changes: production and sandbox are separate instances with
     * separate client registries, so credentials issued in one are not valid in the other.
     */
    public function forget(): void
    {
        $this->disconnect();

        foreach ([self::OPT_CLIENT_ID, self::OPT_CLIENT_SECRET] as $key) {
            delete_option(Options::PREFIX.$key);
        }
    }

    private function tokens(): ?TokenSet
    {
        return TokenSet::fromArray([
            'access_token' => (string) get_option(Options::PREFIX.self::OPT_ACCESS_TOKEN, ''),
            'refresh_token' => (string) get_option(Options::PREFIX.self::OPT_REFRESH_TOKEN, ''),
            'expires_at' => (int) get_option(Options::PREFIX.self::OPT_EXPIRES_AT, 0),
        ]);
    }

    /** Name shown in BillTo, by which the merchant recognises this installation. */
    /**
     * Installation name: unique across BillTo and fixed after registration.
     *
     * Built from the shop host and the current date, so the same shop can register again after
     * disconnecting without colliding with the previous name (BillTo rejects duplicates with
     * 422). Truncated to 50 characters, the limit on the BillTo side.
     */
    private function installationName(): string
    {
        $host = wp_parse_url((string) home_url(), PHP_URL_HOST);
        $host = is_string($host) && $host !== '' ? $host : 'sklep';

        return substr('WooCommerce '.$host.' '.gmdate('Y-m-d H:i'), 0, 50);
    }
}
