<?php

namespace BillTo\Shop\OAuth;

/**
 * BillTo OAuth 2.0 client shared by the shop plugins.
 *
 * Covers Dynamic Client Registration, the Authorization Code flow with PKCE and token refresh.
 * A token issued through this client is scoped to the single company the merchant picks on the
 * consent screen. Transport is injected - see {@see HttpPostInterface}.
 */
final class OAuthClient
{
    /** @var string */
    private $baseUrl;

    /** @var HttpPostInterface */
    private $http;

    public function __construct(string $baseUrl, HttpPostInterface $http)
    {
        $this->baseUrl = rtrim($baseUrl, '/');
        $this->http = $http;
    }

    /**
     * Registers this installation as an OAuth client (RFC 7591).
     *
     * Both credentials are required: `softwareStatementId` identifies the vendor and is issued
     * by BillTo, `code` is a one-time registration code generated by the merchant in BillTo and
     * valid for two minutes. `clientName` must be unique across BillTo and cannot be changed
     * afterwards.
     *
     * @return array{client_id: string, client_secret: string}|null null when registration was refused
     */
    public function register(
        string $softwareStatementId,
        string $code,
        string $clientName,
        string $redirectUri
    ): ?array {
        $response = $this->http->post($this->baseUrl.'/oauth/register', [
            'software_statement_id' => $softwareStatementId,
            'code' => $code,
            'client_name' => $clientName,
            'redirect_uris[0]' => $redirectUri,
        ], ['Accept' => 'application/json']);

        if ($response === null || $response['status'] !== 201) {
            return null;
        }

        $data = json_decode($response['body'], true);

        if (! is_array($data) || ! isset($data['client_id'], $data['client_secret'])) {
            return null;
        }

        return [
            'client_id' => (string) $data['client_id'],
            'client_secret' => (string) $data['client_secret'],
        ];
    }

    /**
     * URL the merchant is sent to in order to approve the integration and pick the company the
     * token will be scoped to.
     *
     * @param  string[]  $scopes
     */
    public function authorizationUrl(
        string $clientId,
        string $redirectUri,
        array $scopes,
        string $state,
        string $codeVerifier
    ): string {
        $query = http_build_query([
            'client_id' => $clientId,
            'redirect_uri' => $redirectUri,
            'response_type' => 'code',
            'scope' => implode(' ', $scopes),
            'state' => $state,
            'code_challenge' => Pkce::challenge($codeVerifier),
            'code_challenge_method' => 'S256',
        ], '', '&');

        return $this->baseUrl.'/oauth/authorize?'.$query;
    }

    /**
     * Exchanges the authorization code for tokens.
     *
     * @return array{access_token: string, refresh_token: ?string, expires_in: int}|null
     */
    public function exchangeCode(
        string $clientId,
        string $clientSecret,
        string $redirectUri,
        string $code,
        string $codeVerifier
    ): ?array {
        return $this->token([
            'grant_type' => 'authorization_code',
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'redirect_uri' => $redirectUri,
            'code' => $code,
            'code_verifier' => $codeVerifier,
        ]);
    }

    /**
     * Exchanges a refresh token for a new pair.
     *
     * The refresh token is single use: BillTo revokes it as part of the exchange, so the new
     * pair has to be stored before the next request.
     *
     * @return array{access_token: string, refresh_token: ?string, expires_in: int}|null
     */
    public function refresh(string $clientId, string $clientSecret, string $refreshToken): ?array
    {
        return $this->token([
            'grant_type' => 'refresh_token',
            'client_id' => $clientId,
            'client_secret' => $clientSecret,
            'refresh_token' => $refreshToken,
        ]);
    }

    /**
     * @param  array<string, string>  $fields
     * @return array{access_token: string, refresh_token: ?string, expires_in: int}|null
     */
    private function token(array $fields): ?array
    {
        $response = $this->http->post($this->baseUrl.'/oauth/token', $fields, ['Accept' => 'application/json']);

        if ($response === null || $response['status'] !== 200) {
            return null;
        }

        $data = json_decode($response['body'], true);

        if (! is_array($data) || ! isset($data['access_token'])) {
            return null;
        }

        return [
            'access_token' => (string) $data['access_token'],
            'refresh_token' => isset($data['refresh_token']) ? (string) $data['refresh_token'] : null,
            // A response without `expires_in` is treated as already expired.
            'expires_in' => isset($data['expires_in']) ? (int) $data['expires_in'] : 0,
        ];
    }
}
